-- Create veterinarians table
CREATE TABLE veterinarians (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_information VARCHAR(255) NOT NULL
);

-- Add veterinarian_id to visits table
ALTER TABLE visits
ADD COLUMN veterinarian_id INT;

-- Add foreign key constraint
ALTER TABLE visits
ADD CONSTRAINT fk_visits_veterinarians
FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id);

-- Optional: Add an index for the foreign key
CREATE INDEX idx_veterinarian_id ON visits (veterinarian_id);
