-- V1__Create_Veterinarian_and_Update_Visit.sql

-- Create veterinarians table
CREATE TABLE veterinarians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_information VARCHAR(255)
);

-- Create visits table if it doesn't exist (assuming a basic structure)
-- If visits table already exists, this part would be skipped or modified.
CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date DATE NOT NULL,
    description VARCHAR(255),
    pet_id BIGINT NOT NULL -- Assuming pet_id exists or will be created
);

-- Add veterinarian_id to visits table
ALTER TABLE visits
ADD COLUMN veterinarian_id BIGINT;

-- Add foreign key constraint
ALTER TABLE visits
ADD CONSTRAINT fk_veterinarian_id
FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id);

-- Optional: Add an index for the foreign key
CREATE INDEX idx_visits_veterinarian_id ON visits (veterinarian_id);
