-- Create veterinarians table
CREATE TABLE veterinarians (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  contact_information VARCHAR(255)
);

-- Create visits_new table with a foreign key to veterinarians
CREATE TABLE visits_new (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_date DATE NOT NULL,
  description VARCHAR(255),
  pet_id INT,
  veterinarian_id INT,
  CONSTRAINT fk_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id)
);