CREATE TABLE veterinarians (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_information VARCHAR(255)
);

ALTER TABLE visits
ADD COLUMN veterinarian_id INT;

ALTER TABLE visits
ADD CONSTRAINT fk_visits_veterinarians
FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id);

INSERT INTO veterinarians (name, contact_information) VALUES ('Dr. James Carter', 'james.carter@petclinic.com');
INSERT INTO veterinarians (name, contact_information) VALUES ('Dr. Helen Leary', 'helen.leary@petclinic.com');