-- V2__Add_veterinarian_and_update_visit.sql

CREATE TABLE veterinarians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_information VARCHAR(255)
);

ALTER TABLE visits
ADD COLUMN veterinarian_id BIGINT;

ALTER TABLE visits
ADD CONSTRAINT fk_visits_veterinarian
FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id);