-- V2__add_veterinarian_and_update_visit.sql

CREATE TABLE veterinarians (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_information VARCHAR(255)
);

ALTER TABLE visits
ADD COLUMN veterinarian_id INT;

ALTER TABLE visits
ADD CONSTRAINT fk_visits_veterinarians FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id);

-- Optional: Add some initial data for veterinarians
INSERT INTO veterinarians (name, contact_information) VALUES ('Dr. James Herriot', 'james.herriot@example.com');
INSERT INTO veterinarians (name, contact_information) VALUES ('Dr. Siegfried Farnon', 'siegfried.farnon@example.com');
INSERT INTO veterinarians (name, contact_information) VALUES ('Dr. Tristan Farnon', 'tristan.farnon@example.com');
