CREATE TABLE veterinarians (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  contact_information VARCHAR(255) NOT NULL
);

ALTER TABLE visits ADD COLUMN veterinarian_id INT;
ALTER TABLE visits ADD CONSTRAINT fk_visits_veterinarians FOREIGN KEY (veterinarian_id) REFERENCES veterinarians (id);
